import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { cookies } from "next/headers";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "./providers/queryClient";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies(); 
  const accessToken = cookieStore.get("access_token")?.value;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
            <QueryClientProvider client={queryClient}>

        <StoreProvider accessToken={accessToken}>
          {children}
        </StoreProvider>
         </QueryClientProvider>
      </body>
    </html>
  );
}